name: Cargo Security Audit

on: push

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Audit
        run: |
          cargo install --force cargo-audit
          cargo generate-lockfile
      - name: Cargo Audit
        run: cargo audit